#include"adc.h"

void Init_ADC(void)
{
	ADC1_DeInit();
        ADC1_Init(ADC1_CONVERSIONMODE_CONTINUOUS, ADC1_CHANNEL_5, ADC1_PRESSEL_FCPU_D2, ADC1_EXTTRIG_TIM, DISABLE, ADC1_ALIGN_RIGHT, ADC1_SCHMITTTRIG_CHANNEL5, ENABLE);
        ADC1_Cmd(ENABLE);
}